/**
 * src/funcion/defaults.js
 * ════════════════════════════════════════════════════════════════════════════
 * Valores por defecto para la base de datos de Rikka-TakaradaMD.
 *
 * Exporta funciones que devuelven objetos frescos (no referencias compartidas)
 * para inicializar usuarios, chats, configuración y mini-juegos.
 *
 * Uso en handler:
 *   import { getDefaultUser, getDefaultChat, getDefaultSettings,
 *            getDefaultAkinator, getDefaultGameGlx } from './src/funcion/defaults.js';
 *
 *   Object.assign(user, { ...getDefaultUser(m.name), ...user });
 * ════════════════════════════════════════════════════════════════════════════
 */

// ══════════════════════════════════════════════════════════════════════════════
// USUARIO
// ══════════════════════════════════════════════════════════════════════════════

/**
 * Devuelve el perfil completo por defecto de un usuario nuevo.
 * @param {string} name - Nombre para el campo `name`.
 */
export function getDefaultUser(name = '') {
  return {
    // ── Identidad ─────────────────────────────────────────────────────────────
    name,
    registered: false,
    reglast: 0,
    regTime: -1,
    unreglast: 0,
    age: -1,
    language: 'es',
    role: 'Novato',
    title: '',
    job: 'Pengangguran',

    // ── Estado ───────────────────────────────────────────────────────────────
    banned: false,
    BannedReason: '',
    Banneduser: false,
    warn: 0,
    mute: false,
    afk: -1,
    afkReason: '',
    wait: 0,

    // ── Economía ─────────────────────────────────────────────────────────────
    money: 15,
    wallet: 0,
    bank: 0,
    atm: 0,
    fullatm: 0,
    coin: 0,
    diamond: 3,
    berlian: 10,
    emerald: 0,
    gems: 0,
    gold: 0,
    emas: 0,
    emasbatang: 0,
    emasbiasa: 0,
    crystal: 0,
    arc: 0,
    arcdurability: 0,

    // ── RPG / Stats ───────────────────────────────────────────────────────────
    exp: 0,
    expg: 0,
    exphero: 0,
    level: 0,
    limit: 20,
    limitjoinfree: 1,
    lbars: '[▒▒▒▒▒▒▒▒▒]',
    health: 100,
    healt: 100,
    healtmonster: 100,
    mana: 20,
    stamina: 100,
    laper: 100,
    haus: 100,
    intelligence: 10,
    agility: 16,
    strength: 30,
    hero: 1,
    herolastclaim: 0,
    pointxp: 0,
    skill: '',
    skillexp: 0,
    tigame: 50,
    rtrofi: 'bronce',
    trofi: 0,
    note: 0,
    pc: 0,

    // ── Mascotas ──────────────────────────────────────────────────────────────
    pet: 0,
    cat: 0,
    catlastfeed: 0,
    catngexp: 0,
    dog: 0,
    dogexp: 0,
    doglastfeed: 0,
    fox: 0,
    foxexp: 0,
    foxlastfeed: 0,
    horse: 0,
    horseexp: 0,
    horselastfeed: 0,
    kyubi: 0,
    naga: 0,
    nagalastclaim: 0,
    griffin: 0,
    griffinexp: 0,
    griffinlastclaim: 0,
    griffinlastfeed: 0,
    centaur: 0,
    centaurexp: 0,
    centaurlastclaim: 0,
    centaurlastfeed: 0,
    phonix: 0,
    phonixexp: 0,
    phonixlastclaim: 0,
    phonixlastfeed: 0,
    dragon: 0,
    dragonexp: 0,
    dragonlastfeed: 0,
    lion: 0,
    lionexp: 0,
    lionlastfeed: 0,
    wolf: 0,
    wolfexp: 0,
    wolflastfeed: 0,
    rhinoceros: 0,
    rhinocerosexp: 0,
    rhinoceroslastfeed: 0,
    kucing: 0,
    kucinglastclaim: 0,
    kuda: 0,
    kudalastclaim: 0,
    rubah: 0,
    rubahlastclaim: 0,
    serigala: 0,
    serigalalastclaim: 0,
    kyubilastclaim: 0,
    panda: 0,
    monyet: 0,
    gajah: 0,

    // ── Comida / Ingredientes ─────────────────────────────────────────────────
    makanan: 0,
    makananpet: 0,
    makanancentaur: 0,
    makanangriffin: 0,
    makanankyubi: 0,
    makanannaga: 0,
    makananphonix: 0,
    makananserigala: 0,
    ayam: 0,
    ayamb: 0,
    ayamg: 0,
    ayambakar: 0,
    ayamgoreng: 0,
    sapi: 0,
    sapir: 0,
    babi: 0,
    babihutan: 0,
    babipanggang: 0,
    kambing: 0,
    banteng: 0,
    kerbau: 0,
    harimau: 0,
    buaya: 0,
    buntal: 0,
    ikan: 0,
    ikanbakar: 0,
    lele: 0,
    leleb: 0,
    leleg: 0,
    lelebakar: 0,
    nila: 0,
    nilabakar: 0,
    dory: 0,
    hiu: 0,
    lobster: 0,
    cumi: 0,
    kepiting: 0,
    kepitingbakar: 0,
    bawal: 0,
    bawalbakar: 0,
    orca: 0,
    lumba: 0,
    paus: 0,
    pausbakar: 0,
    gurita: 0,
    udang: 0,
    udangbakar: 0,
    jagung: 0,
    jagungbakar: 0,
    kentang: 0,
    kentanggoreng: 0,
    bayam: 0,
    kangkung: 0,
    kubis: 0,
    brokoli: 0,
    labu: 0,
    tomat: 0,
    wortel: 0,
    mangga: 0,
    apel: 0,
    jeruk: 0,
    pisang: 0,
    anggur: 0,
    stroberi: 0,
    semangka: 0,
    roti: 0,
    esteh: 0,
    soda: 0,
    vodka: 0,
    aqua: 0,
    sushi: 0,
    sop: 0,
    gulai: 0,
    rendang: 0,
    steak: 0,
    pepesikan: 0,
    gadodado: 0,
    tumiskangkung: 0,
    oporayam: 0,
    fideos: 0,
    bandage: 0,
    botol: 0,
    kaleng: 0,

    // ── Materiales / Craft ────────────────────────────────────────────────────
    kayu: 0,
    wood: 0,
    batu: 0,
    rock: 0,
    coal: 0,
    iron: 0,
    sand: 0,
    clay: 0,
    glass: 0,
    brick: 0,
    kardus: 0,
    sampah: 0,
    trash: 0,
    net: 0,
    string: 0,
    ojekk: 0,

    // ── Armas / Herramientas ──────────────────────────────────────────────────
    weapon: 0,
    weapondurability: 0,
    sword: 0,
    sworddurability: 0,
    katana: 0,
    katanadurability: 0,
    axe: 0,
    axedurability: 0,
    kapak: 0,
    bow: 0,
    bowdurability: 0,
    pickaxe: 0,
    pickaxedurability: 0,
    fishingrod: 0,
    fishingroddurability: 0,
    armor: 0,
    armordurability: 0,
    armormonster: 0,
    shield: 0,
    magicwand: 0,
    magicwanddurability: 0,
    stick: 0,
    roket: 0,
    pancingan: 1,
    umpan: 0,

    // ── Semillas / Jardín ─────────────────────────────────────────────────────
    bibitanggur: 0,
    bibitapel: 0,
    bibitjeruk: 0,
    bibitmangga: 0,
    bibitpisang: 0,
    seedbayam: 0,
    seedbrokoli: 0,
    seedjagung: 0,
    seedkangkung: 0,
    seedkentang: 0,
    seedkubis: 0,
    seedlabu: 0,
    seedtomat: 0,
    seedwortel: 0,
    gardenboxs: 0,
    suplabu: 0,

    // ── Pociones / Rareza ─────────────────────────────────────────────────────
    potion: 10,
    ramuan: 0,
    eleksirb: 0,
    ramuancentaurlast: 0,
    ramuangriffinlast: 0,
    ramuanherolast: 0,
    ramuankucinglast: 0,
    ramuankudalast: 0,
    ramuankyubilast: 0,
    ramuannagalast: 0,
    ramuanphonixlast: 0,
    ramuanrubahlast: 0,
    ramuanserigalalast: 0,
    pillhero: 0,
    common: 0,
    uncoommon: 0,
    superior: 0,
    legendary: 0,
    mythic: 0,
    boxs: 0,
    cupon: 0,
    tiketcoin: 0,

    // ── Misiones / Cooldowns ──────────────────────────────────────────────────
    misi: '',
    lastadventure: 0,
    lastberbru: 0,
    lastberkebon: 0,
    lastbunga: 0,
    lastbunuhi: 0,
    lastcoins: 0,
    lastclaim: 0,
    lastcode: 0,
    lastcofre: 0,
    lastcrusade: 0,
    lastdaang: 0,
    lastdagang: 0,
    lastdiamantes: 0,
    lastduel: 0,
    lastdungeon: 0,
    lasteasy: 0,
    lastfight: 0,
    lastfishing: 0,
    lastgojek: 0,
    lastgrab: 0,
    lasthourly: 0,
    lasthunt: 0,
    lastjb: 0,
    lastkill: 0,
    lastlink: 0,
    lastlumber: 0,
    lastmancingeasy: 0,
    lastmancingextreme: 0,
    lastmancinghard: 0,
    lastmancingnormal: 0,
    lastmining: 0,
    lastmisi: 0,
    lastmonthly: 0,
    lastmulung: 0,
    lastnambang: 0,
    lastnebang: 0,
    lastngocok: 0,
    lastngojek: 0,
    lastopen: 0,
    lastpekerjaan: 0,
    lastpago: 0,
    lastpotionclaim: 0,
    lastramuanclaim: 0,
    lastspam: 0,
    lastrob: 0,
    lastroket: 0,
    lastseen: 0,
    lastSetStatus: 0,
    lastsironclaim: 0,
    lastsmancingclaim: 0,
    laststringclaim: 0,
    lastswordclaim: 0,
    lastturu: 0,
    lastwarpet: 0,
    lastweaponclaim: 0,
    lastweekly: 0,
    lastwork: 0,
    judilast: 0,
    snlast: 0,
    spinlast: 0,

    // ── Trabajos (cooldowns por hora de trabajo) ──────────────────────────────
    kerjasatu: 0, kerjadua: 0, kerjatiga: 0, kerjaempat: 0,
    kerjaenam: 0, kerjalima: 0, kerjatujuh: 0, kerjadelapan: 0,
    kerjasembilan: 0, kerjasepuluh: 0, kerjasebelas: 0, kerjaduabelas: 0,
    kerjatigabelas: 0, kerjaempatbelas: 0, kerjalimabelas: 0, kerjaenambelas: 0,
    kerjatujuhbelas: 0, kerjadelapanbelas: 0, kerjasembilanbelas: 0,
    kerjaduapuluh: 0, kerjaduasatu: 0, kerjaduadua: 0, kerjaduatiga: 0,
    kerjaduaempat: 0, kerjadualima: 0, kerjaduaenam: 0, kerjaduatujuh: 0,
    kerjaduadelapan: 0, kerjaduasembilan: 0, kerjaduabelas: 0, kerjatigapuluh: 0,

    // ── Animales / Cría ───────────────────────────────────────────────────────
    anjing: 0,
    anjinglastclaim: 0,
    anakanjing: 0,
    anakcentaur: 0,
    anakgriffin: 0,
    anakkucing: 0,
    anakkuda: 0,
    anakkyubi: 0,
    anaknaga: 0,
    anakpancingan: 0,
    anakphonix: 0,
    anakrubah: 0,
    anakserigala: 0,
    antispam: 0,
    antispamlastclaim: 0,
    spammer: 0,
    korbanngocok: 0,
    arlok: 0,
    kumba: 0,
    ganja: 0,

    // ── Premium / Suscripción ─────────────────────────────────────────────────
    premium: false,
    premiumTime: 0,
    expired: 0,
    tprem: 0,
    sewa: false,
    joincount: 2,
    joinlimit: 1,

    // ── Misc ──────────────────────────────────────────────────────────────────
    pasangan: '',
    gamemines: false,
    autolevelup: true,
    fortress: 0,
    troopcamp: 0,
    upgrader: 0,
    rumahsakit: 0,

    // ── Gacha / Waifu ─────────────────────────────────────────────────────────
    lastrw: 0,
    gacha_characters: [],
    gacha_favorite: '',
    gacha_claimMsg: '',

    // ── Sub-bot ───────────────────────────────────────────────────────────────
    subbot_requested: false,
    subbot_request_ts: 0,
    subbot_jid: '',
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// AKINATOR
// ══════════════════════════════════════════════════════════════════════════════

export function getDefaultAkinator() {
  return {
    sesi: false,
    server: null,
    frontaddr: null,
    session: null,
    signature: null,
    question: null,
    progression: null,
    step: null,
    soal: null,
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// GAME GALAXY
// ══════════════════════════════════════════════════════════════════════════════

export function getDefaultGameGlx() {
  return {
    status: false,
    notificacao: { recebidas: [] },
    perfil: {
      xp: 112,
      nivel: { nome: 'Iniciante', id: 0, proximoNivel: 1 },
      poder: 500,
      minerando: false,
      nome: null,
      username: null,
      id: null,
      idioma: 'pt-br',
      casa: {
        id: null,
        planeta: null,
        idpelonome: 'terra',
        colonia: { id: 1, nome: null, habitante: false, posicao: { x: 0, y: 0 } },
      },
      carteira: { currency: 'BRL', saldo: 1500 },
      localizacao: {
        status: false, nomeplaneta: null, id: null, idpelonome: null,
        viajando: false, posicao: { x: 0, y: 0 },
      },
      nave: { status: false, id: null, nome: null, velocidade: null, poder: null, valor: null },
      bolsa: {
        itens: { madeira: 1, ferro: 1, diamante: 1, esmeralda: 2, carvao: 1, ouro: 1, quartzo: 1 },
        naves: { status: false, compradas: [] },
      },
      ataque: {
        data: { hora: 0, contagem: 0 },
        sendoAtacado: { status: false, atacante: null },
        forcaAtaque: { ataque: 10 },
      },
      defesa: { forca: 200, ataque: 30 },
    },
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// CHAT (grupo o privado)
// ══════════════════════════════════════════════════════════════════════════════

export function getDefaultChat() {
  return {
    isBanned: false,
    welcome: true,
    detect: true,
    detect2: false,
    sWelcome: '',
    sBye: '',
    sPromote: '',
    sDemote: '',
    antidelete: false,
    modohorny: true,
    autosticker: false,
    audios: true,
    antiLink: false,
    antiLink2: false,
    antiviewonce: false,
    antiToxic: false,
    antiTraba: false,
    antiArab: false,
    antiArab2: false,
    antiporno: false,
    modoadmin: false,
    simi: false,
    game: true,
    expired: 0,
    language: 'es',
    setPrimaryBot: '',
    // ── Gacha ────────────────────────────────────────────────────────────────
    gacha: true,
    gacha_characters: {},
    gacha_rolls: {},
    gacha_sales: {},
    gacha_intercambios: [],
    gacha_timeTrade: 0,
    gacha_regalos: {},
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// SETTINGS (configuración del bot por número)
// ══════════════════════════════════════════════════════════════════════════════

export function getDefaultSettings() {
  return {
    self: false,
    autoread: false,
    autoread2: false,
    restrict: false,
    antiCall: false,
    antiPrivate: false,
    modejadibot: true,
    antispam: false,
    audios_bot: true,
    modoia: false,
  };
}
